(load "~/.emacs.d/global-environment.el")
(load "~/.emacs.d/global-hotkeys.el")
(load "~/.emacs.d/appearance.el")
(load "~/.emacs.d/coding.el")
(load "~/.emacs.d/minibuffer.el")
(load "~/.emacs.d/major-modes-config.el")
